# Generated by Django 5.2.16 on 2026-07-21 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myapp", "0073_firefly_enhancements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DMSProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("paperless", "Paperless-ngx"),
                            ("docspell", "Docspell"),
                            ("papermerge", "PaperMerge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(max_length=500)),
                (
                    "api_token",
                    models.CharField(
                        blank=True,
                        help_text="Paperless-ngx / PaperMerge API token",
                        max_length=512,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, help_text="Docspell username", max_length=255
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Docspell password (stored plaintext; use a dedicated account)",
                        max_length=512,
                    ),
                ),
                (
                    "docspell_collective",
                    models.CharField(
                        blank=True, help_text="Docspell collective name", max_length=255
                    ),
                ),
                (
                    "docspell_source_id",
                    models.CharField(
                        blank=True,
                        help_text="Docspell upload source ID",
                        max_length=255,
                    ),
                ),
                (
                    "auto_push",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically push new attachments to this DMS",
                    ),
                ),
                (
                    "auto_pull",
                    models.BooleanField(
                        default=False,
                        help_text="Periodically pull documents tagged with the VoucherVault tag",
                    ),
                ),
                (
                    "pull_tag",
                    models.CharField(
                        blank=True,
                        help_text="Tag name in the DMS to pull (leave blank to pull all)",
                        max_length=120,
                    ),
                ),
                (
                    "pull_correspondent",
                    models.CharField(
                        blank=True,
                        help_text="Correspondent/source to pull from (optional filter)",
                        max_length=120,
                    ),
                ),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Connected"),
                            ("error", "Error"),
                            ("unchecked", "Not tested"),
                        ],
                        default="unchecked",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dms_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DMS Provider",
                "verbose_name_plural": "DMS Providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DMSSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("push", "Push (VV → DMS)"),
                            ("pull", "Pull (DMS → VV)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Success"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "dms_document_id",
                    models.CharField(
                        blank=True,
                        help_text="Remote document ID in the DMS",
                        max_length=255,
                    ),
                ),
                ("dms_document_title", models.CharField(blank=True, max_length=500)),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dms_sync_logs",
                        to="myapp.document",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dms_sync_logs",
                        to="myapp.item",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="dms.dmsprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "DMS Sync Log",
                "verbose_name_plural": "DMS Sync Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
