# Generated by Django 5.2.16 on 2026-07-27 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("getting-started", "Getting Started"),
                            ("inventory", "Inventory Management"),
                            ("items", "Items"),
                            ("wallets", "Wallets"),
                            ("tags", "Tags"),
                            ("notifications", "Notifications"),
                            ("sharing", "Sharing & Collaboration"),
                            ("settings", "Settings"),
                            ("faq", "FAQ"),
                            ("troubleshooting", "Troubleshooting"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="HTML content for the help topic"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Short description for search",
                        max_length=255,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, help_text="Search tags"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "related_topics",
                    models.ManyToManyField(
                        blank=True, related_name="related_to", to="help.helptopic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Topic",
                "verbose_name_plural": "Help Topics",
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="HelpAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("session_key", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="help.helptopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Access Log",
                "verbose_name_plural": "Help Access Logs",
                "ordering": ["-accessed_at"],
            },
        ),
    ]
