# Generated by Django 5.2.15 on 2026-07-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="file",
            field=models.FileField(upload_to="database/imports/"),
        ),
    ]
