# Generated by Django 5.2.15 on 2026-07-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0002_alter_importjob_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("catima_csv", "Catima CSV"),
                    ("native_csv", "VoucherVault Plus+ CSV Backup"),
                    ("native_json", "VoucherVault Plus+ JSON Backup"),
                ],
                max_length=20,
            ),
        ),
    ]
