"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import logging
import os
import pytz
import secrets
from django.utils.html import escape
from django.utils.translation import gettext_lazy as _
from csp.constants import NONE, SELF, UNSAFE_INLINE, UNSAFE_EVAL

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# get debug modus from env
DEBUG = os.environ.get('DEBUG', 'False').lower() in ['true']

def _read_version_file(filename: str) -> str | None:
    """Reads a plain-text version file baked into the image by docker/Dockerfile."""
    try:
        return (BASE_DIR / filename).read_text().strip() or None
    except OSError:
        return None

# an explicit env var wins (useful for CI/local overrides), then the
# VERSION file shipped in the image, then 'unknown' if neither is present
VERSION = escape(os.environ.get("VERSION") or _read_version_file('VERSION') or 'unknown')

# The upstream l4rm4nd/VoucherVault version this fork's `main` was last
# merged up to date with (see docs/UPSTREAM_SYNC.md) - bumped only when an
# actual upstream sync happens, not on every commit. Lets the app display
# "based on upstream vX.Y.Z" alongside its own VERSION.
UPSTREAM_VERSION = escape(_read_version_file('UPSTREAM_VERSION') or 'unknown')

# auto-generate a secure secret key or use from env variable
SECRET_KEY = os.environ.get("SECRET_KEY", secrets.token_urlsafe(32))

# define allowed hosts and trusted domains via env variables
DOMAIN = ""
ALLOWED_HOSTS = ["127.0.0.1"]
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000"]

DOMAIN = str(os.environ.get("DOMAIN", "localhost"))
TRUSTED_PORT = str(os.environ.get("PORT", "8000"))

if DOMAIN:
    domains = DOMAIN.split(',')
    for domain in domains:
        domain = domain.strip().rstrip('/').replace('http://', '').replace('https://', '')
        if domain:
            ALLOWED_HOSTS.append(domain)
            TRUSTED_USER_DOMAIN_HTTP = f"http://{domain}:{TRUSTED_PORT}"
            TRUSTED_USER_DOMAIN_HTTP_80_DEFAULT = f"http://{domain}"
            TRUSTED_USER_DOMAIN_HTTPS = f"https://{domain}:{TRUSTED_PORT}"
            TRUSTED_USER_DOMAIN_HTTPS_443_DEFAULT = f"https://{domain}"
            CSRF_TRUSTED_ORIGINS.extend([TRUSTED_USER_DOMAIN_HTTP, TRUSTED_USER_DOMAIN_HTTPS, TRUSTED_USER_DOMAIN_HTTP_80_DEFAULT, TRUSTED_USER_DOMAIN_HTTPS_443_DEFAULT])

#Session Management
CSRF_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.environ.get('SESSION_EXPIRE_AT_BROWSER_CLOSE', 'True').lower() in ['true']
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '30')) * 60
SESSION_COOKIE_NAME = 'VVSESS'
SESSION_COOKIE_SAMESITE = 'Lax'

SECURE_COOKIES = os.environ.get('SECURE_COOKIES', 'False').lower() in ['true']

if SECURE_COOKIES:
    # transmit cookies over encrypted https only
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # also set hsts response header
    SECURE_HSTS_SECONDS = "31536000"
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
else:
    # transmit cookies over unencrypted http
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# http security response headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
REFERRER_POLICY = 'same-origin'

# Load from environment, default to "'self'"
raw_frame_ancestors = os.environ.get("CSP_FRAME_ANCESTORS", "'none'")
# Split by comma, strip spaces, and keep properly quoted entries
FRAME_ANCESTORS = [item.strip() for item in raw_frame_ancestors.split(',') if item.strip()]

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],
        "style-src": ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
        "script-src": ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
        "font-src": ["'self'", "https://fonts.googleapis.com", "https://fonts.gstatic.com"],
        "img-src": ["'self'", "data:", "https://img.logo.dev", "https://logo.clearbit.com", "https://www.google.com"],
        "manifest-src": ["'self'"],
        "worker-src": ["'self'"],
        "object-src": ["'none'"],
        "connect-src": ["'self'"],
        "frame-ancestors": FRAME_ANCESTORS,
    },
}

# Application definition
INSTALLED_APPS = [
    'myapp',
    'api',
    'notify',
    'imports',
    'ocr',
    'django_celery_beat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'csp',
    'pwa',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'drf_spectacular',
    'drf_spectacular_sidecar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django_http_referrer_policy.middleware.ReferrerPolicyMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'myapp/templates/registration')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.sidebar_wallets',
                'myapp.context_processors.user_preferences',
                'myapp.context_processors.update_check_status',
                'myapp.context_processors.share_settings',
                'myapp.context_processors.pwa_cache_clear_signal',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DB_ENGINE = os.environ.get("DB_ENGINE", "sqlite3")

if DB_ENGINE == "sqlite3":
    
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'database', 'db.sqlite3'),
    }
}

elif DB_ENGINE == "postgres":

    DB_HOST = os.environ.get("POSTGRES_HOST", "db")
    DB_PORT = os.environ.get("POSTGRES_PORT", "5432")
    DB_USER = os.environ.get("POSTGRES_USER", "vouchervault")
    DB_PASSWORD = os.environ.get("POSTGRES_PASSWORD", "vouchervault")
    DB_NAME = os.environ.get("POSTGRES_DB", "vouchervault")

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
LANGUAGE_CODE = 'en'
TIME_ZONE = os.environ.get('TZ', 'Europe/Berlin')
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('de', _('German')),
    ('fr', _('French')),
    ('it', _('Italian')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

# Celery configuration
# http://docs.celeryproject.org/en/latest/configuration.html
LOGS_DIR = os.path.join(BASE_DIR, 'logs')

REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL == None:
    CELERY_BROKER_URL = 'redis://redis:6379/0'
    CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
else:
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL

# The same Redis instance Celery already requires, on a separate logical
# DB (index 1) so its keys don't mix with Celery's broker/result data.
# Used for rate-limiting the public share link view (myapp/public_share.py)
# - needs a store shared across uWSGI worker processes, which Django's
# default LocMemCache is not. Rebuilt via urlsplit rather than naive string
# splitting since REDIS_URL isn't guaranteed to already end in a DB index.
from urllib.parse import urlsplit, urlunsplit

_redis_cache_parts = urlsplit(REDIS_URL or 'redis://redis:6379/0')
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': urlunsplit(_redis_cache_parts._replace(path='/1')),
    }
}


CELERY_WORKER_CONCURRENCY = int(os.environ.get('CELERY_WORKER_CONCURRENCY', '1'))
CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.environ.get('CELERY_WORKER_PREFETCH_MULTIPLIER', '1'))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Berlin'
DJANGO_CELERY_BEAT_TZ_AWARE = True
CELERY_ENABLE_UTC = False
CELERY_WORKER_LOG_FILE = os.path.join(LOGS_DIR, 'celery_worker.log')
CELERY_BEAT_LOG_FILE = os.path.join(LOGS_DIR, 'celery_beat.log')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'myapp', 'static')

PWA_APP_NAME = 'VoucherVault Plus+'
PWA_APP_DESCRIPTION = 'VoucherVault Plus+ voucher and loyalty card management.'
PWA_APP_THEME_COLOR = '#4154f1'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
  {
    'src': '/static/assets/img/manifest-icon-192.png',
    'sizes': '192x192',
    'type': 'image/png',
    'purpose': 'any'
  },
  {
    'src': '/static/assets/img/manifest-icon-192.maskable.png',
    'sizes': '192x192',
    'type': 'image/png',
    'purpose': 'maskable'
  },
  {
    'src': '/static/assets/img/manifest-icon-512.png',
    'sizes': '512x512',
    'type': 'image/png',
    'purpose': 'any'
  },
  {
    'src': '/static/assets/img/manifest-icon-512.maskable.png',
    'sizes': '512x512',
    'type': 'image/png',
    'purpose': 'maskable'
  }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/assets/img/apple-icon-180.png',
        'sizes': '180x180',
    },
]
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'myapp', 'serviceworker.js')

# REST API (token + session auth; every queryset in `api/` is scoped to
# request.user, see api/views.py). Swagger/OpenAPI assets are served from the
# sidecar package (no CDN) so they work under the strict CSP above and in
# fully offline/self-hosted deployments.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Only write requests (POST/PUT/PATCH/DELETE) are throttled - see
    # api/throttling.py::WriteRateThrottle. Reads are left unlimited since
    # the API previously had no rate limiting at all, and a leaked token
    # or misbehaving script could otherwise hammer writes with zero
    # backpressure.
    'DEFAULT_THROTTLE_CLASSES': ['api.throttling.WriteRateThrottle'],
    'DEFAULT_THROTTLE_RATES': {
        'write': os.environ.get('API_WRITE_RATE_LIMIT', '60/minute'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'VoucherVault Plus+ API',
    'DESCRIPTION': 'REST API for managing vouchers, gift cards, coupons and loyalty cards.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
}

# --------------------------------------------------------------------------
# Fork-added feature toggles & integrations. Every optional env var this
# fork reads lives here, in one place, instead of scattered `os.environ.get()`
# calls through the codebase (the previous approach meant EXPIRY_THRESHOLD_DAYS
# alone was read with its default re-typed in six different files). Other
# modules read these via `django.conf.settings`, never `os.environ` directly,
# so `docker/env.example` and this block are the only two places a new env
# var needs documenting — the docker-compose files pass everything through
# via `env_file` and never need editing for a new var.
# --------------------------------------------------------------------------

# ---- Expiry notifications ----
EXPIRY_THRESHOLD_DAYS = int(os.environ.get('EXPIRY_THRESHOLD_DAYS', 30))
EXPIRY_LAST_NOTIFICATION_DAYS = int(os.environ.get('EXPIRY_LAST_NOTIFICATION_DAYS', 7))
EXPIRY_THRESHOLD_DAYS_FINAL = int(os.environ.get('EXPIRY_THRESHOLD_DAYS_FINAL', EXPIRY_LAST_NOTIFICATION_DAYS))
NTFY_DEFAULT_SERVER = os.environ.get('NTFY_DEFAULT_SERVER', 'https://ntfy.sh')

# ---- Web Push notification backend ----
WEBPUSH_VAPID_PUBLIC_KEY = os.environ.get('WEBPUSH_VAPID_PUBLIC_KEY') or None
WEBPUSH_VAPID_PRIVATE_KEY = os.environ.get('WEBPUSH_VAPID_PRIVATE_KEY') or None
WEBPUSH_VAPID_CLAIMS_EMAIL = os.environ.get('WEBPUSH_VAPID_CLAIMS_EMAIL', 'mailto:admin@example.com')

# ---- Merchant logos ----
MERCHANT_LOGOS_ENABLED = os.environ.get('MERCHANT_LOGOS_ENABLED', 'true').lower() in ('true', '1', 'yes')

# ---- OCR ("Scan with AI") ----
OCR_BACKEND = os.environ.get('OCR_BACKEND', 'none').lower()
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY') or None
ANTHROPIC_OCR_MODEL = os.environ.get('ANTHROPIC_OCR_MODEL', 'claude-sonnet-5')
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY') or None
OPENAI_OCR_MODEL = os.environ.get('OPENAI_OCR_MODEL', 'gpt-4o-mini')

# ---- Apple Wallet (.pkpass) export ----
PKPASS_CERT_PATH = os.environ.get('PKPASS_CERT_PATH') or None
PKPASS_CERT_PASSWORD = os.environ.get('PKPASS_CERT_PASSWORD') or None
PKPASS_WWDR_CERT_PATH = os.environ.get('PKPASS_WWDR_CERT_PATH') or None
PKPASS_TEAM_ID = os.environ.get('PKPASS_TEAM_ID') or None
PKPASS_PASS_TYPE_ID = os.environ.get('PKPASS_PASS_TYPE_ID') or None
PKPASS_ORGANIZATION_NAME = os.environ.get('PKPASS_ORGANIZATION_NAME', 'VoucherVault Plus+')

# ---- Google Wallet export ----
GOOGLE_WALLET_SERVICE_ACCOUNT_KEY_PATH = os.environ.get('GOOGLE_WALLET_SERVICE_ACCOUNT_KEY_PATH') or None
GOOGLE_WALLET_ISSUER_ID = os.environ.get('GOOGLE_WALLET_ISSUER_ID') or None
GOOGLE_WALLET_CLASS_ID = os.environ.get('GOOGLE_WALLET_CLASS_ID') or None

# ---- Update check (GitHub Releases) ----
# On by default; makes one outbound request per periodic task run to the
# public GitHub Releases API for UPDATE_CHECK_REPO. Set to False to
# disable entirely if you don't want this instance making outbound calls.
UPDATE_CHECK_ENABLED = os.environ.get('UPDATE_CHECK_ENABLED', 'true').lower() in ('true', '1', 'yes')
UPDATE_CHECK_REPO = os.environ.get('UPDATE_CHECK_REPO', 'gregbtm/VoucherVault')

# Optional: Portainer's per-stack redeploy webhook URL. When set, superusers
# get a "Redeploy now" button on the update-available banner above, which
# POSTs to this URL server-side (see myapp/portainer.py) - i.e. over the
# Docker network Portainer and this container already share, so nothing
# needs to be exposed to the internet for this button to work. Unset by
# default; the button is hidden entirely if this isn't configured.
PORTAINER_WEBHOOK_URL = os.environ.get('PORTAINER_WEBHOOK_URL') or None

# ---- Scheduled local backups ----
# On by default. A periodic Celery task writes a Full Backup zip (same
# format as the manual export) per user to database/backups/<username>/ -
# the same bind-mounted volume as uploads/documents - and rotates old ones.
SCHEDULED_BACKUP_ENABLED = os.environ.get('SCHEDULED_BACKUP_ENABLED', 'true').lower() in ('true', '1', 'yes')
BACKUP_RETENTION_COUNT = int(os.environ.get('BACKUP_RETENTION_COUNT', 7))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django's own default LOGGING config only prints tracebacks to console
# when DEBUG=True; with DEBUG=False (this app's production default) an
# unhandled exception instead only tries to email ADMINS (unconfigured
# here, so it silently goes nowhere) - meaning server errors left zero
# trace in `docker logs` before this. Explicit config below always logs
# to stdout regardless of DEBUG, so a real deployment's container logs
# actually show what broke.
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        # Full tracebacks for every unhandled exception (500, level ERROR)
        # that Django's exception middleware catches, plus 404s (level
        # WARNING) and other 4xx - unconditionally, regardless of DEBUG.
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Quiets Django's normal per-request access log (GET /items/... 200)
        # down to warnings only - runserver/gunicorn access logs cover that
        # already and this would otherwise double up with LOG_LEVEL=INFO.
        'django.server': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/post-logout/'

WSGI_APPLICATION = 'myproject.wsgi.application'

# check if oidc is enabled
OIDC_ENABLED = os.environ.get('OIDC_ENABLED', 'False').lower() in ['true']
OIDC_AUTOLOGIN = os.environ.get('OIDC_AUTOLOGIN', 'False').lower() in ['true']

if OIDC_ENABLED:
    # get oidc config from env
    OIDC_CREATE_USER = os.environ.get('OIDC_CREATE_USER', 'True').lower() in ['true']
    OIDC_RP_SIGN_ALGO = os.environ.get('OIDC_RP_SIGN_ALGO', 'HS256')
    OIDC_RP_IDP_SIGN_KEY = os.environ.get('OIDC_RP_IDP_SIGN_KEY')
    OIDC_RP_CLIENT_ID = os.environ.get('OIDC_RP_CLIENT_ID', "vouchervault")
    OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_RP_CLIENT_SECRET')
    OIDC_USERNAME_ALGO = 'myapp.utils.generate_username'

    # Optional: instead of configuring every OIDC_OP_*_ENDPOINT by hand,
    # point OIDC_DISCOVERY_URL at the provider's
    # .well-known/openid-configuration document (e.g.
    # https://auth.example.com/.well-known/openid-configuration) and the
    # individual endpoints are read from it automatically. Any endpoint
    # set explicitly via its own env var always wins over the discovered
    # value - this is additive/opt-in, not a replacement for manual
    # configuration. mozilla-django-oidc itself has no discovery support
    # (upstream closed this as not-planned - l4rm4nd/VoucherVault#67,
    # citing mozilla/mozilla-django-oidc#414) - this fetches the document
    # once at startup, before mozilla-django-oidc ever reads these
    # settings, so it works with any provider without waiting on that
    # library to add the feature.
    _oidc_discovery_url = os.environ.get('OIDC_DISCOVERY_URL')
    _oidc_discovered = {}
    if _oidc_discovery_url:
        from myapp.utils import fetch_oidc_discovery
        _oidc_discovered = fetch_oidc_discovery(_oidc_discovery_url)
        if _oidc_discovered:
            logging.getLogger(__name__).info(
                "OIDC discovery: fetched provider configuration from %s", _oidc_discovery_url
            )

    OIDC_OP_AUTHORIZATION_ENDPOINT = os.environ.get('OIDC_OP_AUTHORIZATION_ENDPOINT') or _oidc_discovered.get('authorization_endpoint')
    OIDC_OP_TOKEN_ENDPOINT = os.environ.get('OIDC_OP_TOKEN_ENDPOINT') or _oidc_discovered.get('token_endpoint')
    OIDC_OP_USER_ENDPOINT = os.environ.get('OIDC_OP_USER_ENDPOINT') or _oidc_discovered.get('userinfo_endpoint')
    OIDC_OP_JWKS_ENDPOINT = os.environ.get('OIDC_OP_JWKS_ENDPOINT') or _oidc_discovered.get('jwks_uri')
    #ALLOW_LOGOUT_GET_METHOD = True

    # Add 'mozilla_django_oidc.middleware.SessionRefresh' to INSTALLED_APPS
    INSTALLED_APPS.append('mozilla_django_oidc')
    
    # Add 'mozilla_django_oidc' authentication backend
    AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.ModelBackend',
        'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    )

    # Add 'mozilla_django_oidc.middleware.SessionRefresh' to MIDDLEWARE
    # https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html#validate-id-tokens-by-renewing-them
    # disabled atm, as it leads to a circular import with container error "partially initialized module 'josepy'"
    #MIDDLEWARE.append('mozilla_django_oidc.middleware.SessionRefresh')

    # Fix http callback issue in mozilla-django-oidc by forcing https; https://github.com/mozilla/mozilla-django-oidc/issues/417
    # OIDC should only be setup behind a TLS reverse proxy anyways
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
