# Generated by Django 5.2.15 on 2026-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_item_notes_tag_item_tags_wallet_item_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="notify_days_before",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Override the global expiry notification threshold for this item (in days).",
                null=True,
            ),
        ),
    ]
