# Generated by Django 5.2.15 on 2026-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0032_item_notify_days_before"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("csv_import", "CSV Import"),
                    ("api", "API"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
