# Generated by Django 5.2.15 on 2026-07-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0035_wallet_shared_with_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="card_number",
            field=models.CharField(
                blank=True,
                help_text="Printed member/account number, if different from the barcode's encoded value. Falls back to the redeem code when blank.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Hide from the default inventory view without marking it used or deleting it.",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="keep_screen_awake",
            field=models.BooleanField(
                default=True,
                help_text="Keep the screen on while viewing an item's barcode.",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="oled_dark_mode",
            field=models.BooleanField(
                default=False,
                help_text="Use true-black surfaces in dark mode (OLED screens).",
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="sort_by",
            field=models.CharField(
                choices=[
                    ("expiry_date", "Expiry Date"),
                    ("name", "Name"),
                    ("issue_date", "Creation Date"),
                    ("value", "Value"),
                    ("last_used_at", "Last Used"),
                ],
                default="expiry_date",
                max_length=20,
            ),
        ),
    ]
