# Generated by Django 5.2.15 on 2026-07-11 02:00

from django.db import migrations


def relabel_currency_to_gbp(apps, schema_editor):
    """
    Relabels every existing item and user preference to GBP. This changes
    the currency code only — the numeric value/balance is left untouched,
    so a "5.00 EUR" gift card becomes a "5.00 GBP" gift card, not a
    converted amount.
    """
    Item = apps.get_model('myapp', 'Item')
    UserPreference = apps.get_model('myapp', 'UserPreference')
    Item.objects.exclude(currency='GBP').update(currency='GBP')
    UserPreference.objects.exclude(default_currency='GBP').update(default_currency='GBP')


def relabel_currency_to_eur(apps, schema_editor):
    """Reverse is a no-op: the original currency labels aren't recoverable
    once relabeled, and re-labeling everything back to EUR would be wrong
    for any items that were genuinely GBP already or another currency."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0037_gbp_default_currency"),
    ]

    operations = [
        migrations.RunPython(relabel_currency_to_gbp, relabel_currency_to_eur),
    ]
