# Generated by Django 5.2.15 on 2026-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0038_convert_existing_items_to_gbp"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="balance_check_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the merchant's balance/validity check page for this gift card. Not a live check — VoucherVault has no way to query balances itself.",
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="balance_check_url",
            field=models.URLField(
                blank=True,
                help_text="Remembered gift-card balance/validity check link for this merchant, suggested on future gift cards from the same issuer.",
            ),
        ),
    ]
