# Generated by Django 5.2.15 on 2026-07-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0039_item_balance_check_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateCheckStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latest_version", models.CharField(blank=True, max_length=50)),
                ("latest_release_url", models.URLField(blank=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("update_available", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Update Check Status",
                "verbose_name_plural": "Update Check Status",
            },
        ),
    ]
