# Generated by Django 5.2.15 on 2026-07-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0040_updatecheckstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="offline_cache_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show the 'Cache for Offline' option in the sidebar. Turning this off purges any existing offline cache.",
            ),
        ),
    ]
