# Generated by Django 5.2.15 on 2026-07-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0044_alter_userprofile_ics_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry_threshold_days", models.PositiveIntegerField(default=30)),
                (
                    "expiry_last_notification_days",
                    models.PositiveIntegerField(default=7),
                ),
                (
                    "ntfy_default_server",
                    models.CharField(
                        blank=True, default="https://ntfy.sh", max_length=255
                    ),
                ),
                (
                    "webpush_vapid_public_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "webpush_vapid_private_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "webpush_vapid_claims_email",
                    models.CharField(
                        blank=True, default="mailto:admin@example.com", max_length=255
                    ),
                ),
                ("merchant_logos_enabled", models.BooleanField(default=True)),
                (
                    "ocr_backend",
                    models.CharField(
                        choices=[
                            ("none", "Disabled"),
                            ("claude", "Claude"),
                            ("openai", "OpenAI"),
                            ("tesseract", "Tesseract (local, free)"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "anthropic_api_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "anthropic_ocr_model",
                    models.CharField(
                        blank=True, default="claude-sonnet-5", max_length=100
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "openai_ocr_model",
                    models.CharField(blank=True, default="gpt-4o-mini", max_length=100),
                ),
                (
                    "pkpass_cert_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "pkpass_cert_password",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "pkpass_wwdr_cert_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "pkpass_team_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "pkpass_pass_type_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "pkpass_organization_name",
                    models.CharField(
                        blank=True, default="VoucherVault Plus+", max_length=255
                    ),
                ),
                (
                    "google_wallet_service_account_key_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "google_wallet_issuer_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "google_wallet_class_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("update_check_enabled", models.BooleanField(default=True)),
                (
                    "update_check_repo",
                    models.CharField(
                        blank=True, default="gregbtm/VoucherVault", max_length=255
                    ),
                ),
                (
                    "portainer_webhook_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("scheduled_backup_enabled", models.BooleanField(default=True)),
                ("backup_retention_count", models.PositiveIntegerField(default=7)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
