# Generated by Django 5.2.15 on 2026-07-12 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0046_seed_siteconfiguration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="share_via_smart_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Let 'Share via...' offer a choice between a bare link and a rich share (merchant, code, PIN, remaining balance) via a public, no-login-required link. Off reverts to the classic single-tap share.",
            ),
        ),
        migrations.CreateModel(
            name="ItemPublicShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_share",
                        to="myapp.item",
                    ),
                ),
            ],
        ),
    ]
