# Generated by Django 5.2.15 on 2026-07-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0047_siteconfiguration_share_via_smart_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempublicshare",
            name="access_pin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional short code required to view this link, separate from the item's own redemption PIN (Item.pin, shown on the page itself). Only set when SiteConfiguration.share_link_pin_enabled was on at creation/regeneration time. Shown to the owner on the item detail page to relay separately from the link itself - not stored as a hash, same plaintext-at-rest posture this app already takes with redeem codes and item PINs.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="itempublicshare",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Blank means never expires. Set from SiteConfiguration.share_link_expiry_days at creation/regeneration time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itempublicshare",
            name="failed_pin_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lifetime count of wrong access-code guesses, surfaced to the owner as an early warning sign of probing. Not reset on a successful unlock.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="share_link_expiry_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="How long a new/regenerated public share link stays valid. 0 means it never expires.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="share_link_pin_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Require a short access code to view a public share link, on top of the link itself. The code is shown to you on the item page to relay separately (call, text, in person) - it is never automatically included in the shared text/link itself.",
            ),
        ),
    ]
