# Generated by Django 5.2.15 on 2026-07-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0048_itempublicshare_access_pin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="updatecheckstatus",
            name="last_check_error",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Set when the most recent check couldn't reach GitHub or got an unexpected response; cleared on the next successful check. Blank with a recent checked_at means GitHub was reachable.",
                max_length=500,
            ),
        ),
    ]
