# Generated by Django 5.2.15 on 2026-07-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0049_updatecheckstatus_last_check_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="blur_codes_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Blur barcodes and redeem codes until tapped. Turn off for faster access at point-of-sale.",
            ),
        ),
    ]
