# Generated by Django 5.2.15 on 2026-07-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0050_userpreference_blur_codes_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpstreamSyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upstream_repo",
                    models.CharField(default="l4rm4nd/VoucherVault", max_length=255),
                ),
                ("latest_version", models.CharField(blank=True, max_length=50)),
                ("latest_release_url", models.URLField(blank=True)),
                (
                    "latest_release_published_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_check_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "verbose_name": "Upstream Sync Status",
                "verbose_name_plural": "Upstream Sync Status",
            },
        ),
    ]
