# Generated by Django 5.2.15 on 2026-07-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0051_upstreamsyncstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_dev_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional logo.dev publishable key (pk_...). When set, logo.dev is tried first for merchant logos - a dedicated logo API with consistently higher-resolution real brand marks than the Clearbit/Google-favicon fallbacks used otherwise. Get one at https://logo.dev.",
                max_length=255,
            ),
        ),
    ]
