# Generated by Django 5.2.15 on 2026-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0052_siteconfiguration_logo_dev_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image_phash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Perceptual hash of `file`, for duplicate-photo detection. Computed automatically on save - never set this by hand.",
                max_length=16,
            ),
        ),
    ]
