# Generated by Django 5.2.15 on 2026-07-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0053_item_image_phash"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="next_up_wallet",
            field=models.ForeignKey(
                blank=True,
                help_text="Highlight the soonest-expiring item from this wallet at the top of Inventory (e.g. a 'Train Tickets' wallet, to always surface the next one to use). Off if unset.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="myapp.wallet",
            ),
        ),
    ]
