# Generated by Django 5.2.15 on 2026-07-16 12:20

import django.core.validators
from django.db import migrations, models


def copy_next_up_wallet_into_wallets(apps, schema_editor):
    """
    Preserves any existing single-wallet preference (from the previous
    next_up_wallet FK, shipped just before this migration) into the new
    next_up_wallets many-to-many, before that FK column is dropped.
    """
    UserPreference = apps.get_model('myapp', 'UserPreference')
    for preference in UserPreference.objects.exclude(next_up_wallet=None):
        preference.next_up_wallets.add(preference.next_up_wallet)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0054_userpreference_next_up_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="next_up_max_items",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many upcoming items to show in the Next Up widget, soonest first (1-3).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="next_up_wallets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Highlight the soonest-expiring items from these wallets at the top of Inventory (e.g. a 'Train Tickets' wallet, to always surface the next one to use). Empty means off.",
                related_name="+",
                to="myapp.wallet",
            ),
        ),
        migrations.RunPython(copy_next_up_wallet_into_wallets, noop_reverse),
        migrations.RemoveField(
            model_name="userpreference",
            name="next_up_wallet",
        ),
    ]
