# Generated by Django 5.2.15 on 2026-07-16 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0055_remove_userpreference_next_up_wallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="calendar_months_ahead",
            field=models.PositiveIntegerField(
                default=3,
                help_text="How many months ahead the Dashboard's expiry calendar shows.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="duplicate_photo_threshold",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Hamming-distance sensitivity (out of 64 bits) for flagging two uploaded card photos as likely duplicates. Lower is stricter (fewer false-positive matches, but might miss a genuine duplicate shot at a different angle/lighting); higher is looser.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(64),
                ],
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="expiring_soon_limit",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Max items shown in the Dashboard's 'Expiring Soon' list.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="wallet_chart_limit",
            field=models.PositiveIntegerField(
                default=8,
                help_text="How many wallets show individually in the 'Items by Wallet' chart before folding the rest into \"Other\".",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
