# Generated by Django 5.2.15 on 2026-07-16 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0056_siteconfiguration_calendar_months_ahead_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="journey_destination",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Arrival station/stop for a train or transport ticket, e.g. "London Terminals" or "LON".',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="journey_origin",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Departure station/stop for a train or transport ticket, e.g. "Hatfield Peverel" or "HAP". Powers the Active Today widget - leave blank for anything that isn\'t a point-to-point travel ticket.',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="active_today_cutoff_time",
            field=models.TimeField(
                default=datetime.time(12, 0),
                help_text="Before this time, Active Today shows today's outward leg (home station as origin). From this time on, the outward leg is marked used and the return leg (home station as destination) is shown instead.",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="active_today_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Show the Active Today widget - surfaces today's outward or return leg of a round-trip ticket (e.g. a daily commute), switching over at the cutoff time below. Requires a home station to be set.",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="commute_home_station",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Your home station/stop. Matched case-insensitively against a ticket\'s journey origin/destination to tell an outward leg from a return leg, e.g. "Hatfield Peverel" or "HAP" - use whatever your tickets actually print.',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="auto_assign_issuer_match",
            field=models.CharField(
                blank=True,
                default="",
                help_text='New items whose issuer contains this text (case-insensitive) are automatically placed in this wallet, unless a wallet was already chosen. E.g. "National Rail" to route scanned train tickets straight into a "Train Tickets" wallet.',
                max_length=100,
            ),
        ),
    ]
