# Generated by Django 5.2.15 on 2026-07-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0057_item_journey_destination_item_journey_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="travel_time",
            field=models.TimeField(
                blank=True,
                help_text="Scheduled departure/travel time for a Travel Pass, if known - leave blank otherwise (many train tickets are date-only, with no fixed time).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("voucher", "Voucher"),
                    ("giftcard", "Gift Card"),
                    ("coupon", "Coupon"),
                    ("loyaltycard", "Loyalty Card"),
                    ("travelpass", "Travel Pass"),
                ],
                max_length=100,
            ),
        ),
    ]
