# Generated by Django 5.2.15 on 2026-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0059_scanfieldcorrection"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="discount_applied",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Discount or railcard applied at purchase, e.g. "Network Railcard". Informational only.',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="order_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Merchant/booking order or confirmation reference, if different from the redeem code - e.g. a rail ticket's order ID alongside its separate ticket number. Optional for any item type.",
                max_length=100,
            ),
        ),
    ]
