# Generated by Django 5.2.15 on 2026-07-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0060_item_discount_applied_item_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="tilt_scan_detection_enabled",
            field=models.BooleanField(
                default=False,
                help_text="On an item's page, suggest marking it Used when you tilt your phone forward - the motion of presenting a barcode to a reader (train barriers, a till scanner). Requires enabling motion access once per device; never marks an item used on its own, only suggests it.",
            ),
        ),
    ]
