# Generated by Django 5.2.15 on 2026-07-18 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0061_userpreference_tilt_scan_detection_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="nearby_places_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow the opt-in 'Nearby' widget to query OpenStreetMap's Overpass API with a user's one-shot location, matched against their item issuers. Off disables the feature site-wide regardless of each user's own preference.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="overpass_api_url",
            field=models.CharField(
                blank=True,
                default="https://overpass-api.de/api/interpreter",
                help_text="Overpass API endpoint. Point this at your own instance to avoid the public one's rate limits - see https://wiki.openstreetmap.org/wiki/Overpass_API/Installation.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="nearby_items_enabled",
            field=models.BooleanField(
                default=False,
                help_text='On Inventory, ask for your location once and suggest items whose issuer matches a shop near you right now (e.g. "You\'re near Tesco - 2 items here"). A one-shot lookup only - never tracks your location in the background. Looked up via OpenStreetMap; no account or API key needed.',
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="nearby_radius_m",
            field=models.PositiveIntegerField(
                default=150,
                help_text="How far around your current location to look for a matching shop, in metres.",
                validators=[
                    django.core.validators.MinValueValidator(25),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
