# Generated by Django 5.2.15 on 2026-07-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0062_siteconfiguration_nearby_places_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text extracted from the document by OCR, populated automatically after upload when OCR is enabled.",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_recurring",
            field=models.BooleanField(
                default=False,
                help_text="This item renews periodically (subscription, annual pass, etc.).",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="renewal_date",
            field=models.DateField(
                blank=True,
                help_text="Next renewal / billing date for recurring items.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="renewal_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("biannual", "Every 6 months"),
                    ("annual", "Annual"),
                ],
                help_text="How often this item renews.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="budget_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional monthly spending budget for this wallet. When set, a progress bar shows how much of the budget has been spent in the current calendar month.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
