# Generated by Django 5.2.15 on 2026-07-19 01:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0063_phase102_budget_recurring_ocr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["user", "is_used", "expiry_date"], name="item_user_used_expiry"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["user", "type", "is_used"], name="item_user_type_used"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["user", "is_archived", "is_used"],
                name="item_user_archived_used",
            ),
        ),
    ]
