# Generated by Django 5.2.16 on 2026-07-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0071_item_firefly_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="notifications_muted",
            field=models.BooleanField(
                default=False,
                help_text="Suppress all notification rules for this item (expiry warnings, renewal alerts, etc.).",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="firefly_account_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Firefly III asset account ID linked to this item. Set via 'Link to Firefly III' or enter manually.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userwebhook",
            name="secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional HMAC-SHA256 signing secret. When set, each request includes an X-VoucherVault-Signature header.",
                max_length=64,
            ),
        ),
    ]
