# Generated by Django 5.2.16 on 2026-07-20 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0072_item_notifications_muted"),
        ("notify", "0004_firefly_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="firefly_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Override which Firefly III notification rule handles this item's balance sync. Falls back to wallet-level rule, then user's first enabled Firefly rule.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="notify.notificationrule",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="firefly_transaction_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Firefly III transaction ID after a successful sync. Blank means unsynced or Firefly not configured.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="firefly_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Firefly III notification rule used for items in this wallet. Overrides user default; overridden by per-item setting.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="notify.notificationrule",
            ),
        ),
    ]
