# Generated by Django 5.2.16 on 2026-07-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0074_siteconfiguration_gift_card_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="vv_base_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Public base URL of this VoucherVault installation (e.g. https://vault.example.com). Used to build clickable links in ntfy notifications. Leave blank to omit links.",
                max_length=255,
            ),
        ),
    ]
