# Generated by Django 5.2.16 on 2026-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0075_siteconfiguration_vv_base_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="wallet",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
