# Generated by Django 5.2.16 on 2026-07-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0076_wallet_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="allow_registration",
            field=models.BooleanField(
                default=True,
                help_text="Allow new users to register accounts. Disable to make the instance invite-only (existing users and social/OIDC logins are unaffected).",
            ),
        ),
        migrations.CreateModel(
            name="BalanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_history",
                        to="myapp.item",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
            },
        ),
    ]
