# Generated by Django 5.2.16 on 2026-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0077_balance_history_allow_registration_sitecache"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="webpush_barcode_key_version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Incrementing this value invalidates all previously issued barcode push-image tokens, forcing new tokens to be generated on the next notification send. Rotate this if you suspect a token has been captured in transit.",
            ),
        ),
    ]
