# Generated by Django 5.2.16 on 2026-07-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0083_pocketid_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_from_address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="From address for outbound emails (e.g. vault@example.com). Defaults to the SMTP username.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_host",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SMTP server hostname (e.g. smtp.gmail.com). Leave blank to disable outbound email.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_host_password",
            field=models.CharField(
                blank=True, default="", help_text="SMTP login password.", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_host_user",
            field=models.CharField(
                blank=True, default="", help_text="SMTP login username.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_port",
            field=models.PositiveIntegerField(
                default=587,
                help_text="SMTP port. 587 for STARTTLS, 465 for SSL, 25 for plain.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_use_ssl",
            field=models.BooleanField(
                default=False,
                help_text="Use implicit SSL (port 465). Mutually exclusive with STARTTLS.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_use_tls",
            field=models.BooleanField(
                default=True,
                help_text="Use STARTTLS (recommended for port 587). Disable if using SSL on port 465.",
            ),
        ),
    ]
