# Generated by Django 5.2.16 on 2026-07-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0085_userpreference_email_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitelink",
            name="accepted_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address recorded when the invite was accepted.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invitelink",
            name="custom_expiry_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Per-invite expiry override in days. Null means use the site default.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invitelink",
            name="pocket_id_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PocketID username assigned at provisioning time.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="invitelink",
            name="pre_share_wallet",
            field=models.ForeignKey(
                blank=True,
                help_text="Wallet to automatically share with the invitee when they accept.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invite_pre_shares",
                to="myapp.wallet",
            ),
        ),
        migrations.AddField(
            model_name="invitelink",
            name="welcome_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional custom message included in the invite email body.",
            ),
        ),
    ]
