# Generated by Django 5.2.16 on 2026-07-27 06:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0088_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemEnrichmentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrichment_run_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Groups changes from the same enrichment operation together.",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Name of the field that was changed (e.g., 'expiry_date', 'issuer').",
                        max_length=100,
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True,
                        help_text="Previous value before enrichment.",
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, help_text="New value after enrichment.", null=True
                    ),
                ),
                (
                    "enrichment_type",
                    models.CharField(
                        choices=[
                            (
                                "ocr_rescan",
                                "OCR Rescan - Re-extracted from attached document",
                            ),
                            (
                                "merchant_lookup",
                                "Merchant Lookup - Matched against merchant database",
                            ),
                            (
                                "validation",
                                "Validation - Normalized/corrected field values",
                            ),
                            (
                                "auto_enrich",
                                "Auto Enrichment - Populated from enrichment pipeline",
                            ),
                        ],
                        help_text="What type of enrichment produced this change.",
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score (0-1) for this enriched value, if applicable.",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable explanation of why this field was changed.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who triggered this enrichment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_logs",
                        to="myapp.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["enrichment_run_id", "created_at"],
                        name="myapp_iteme_enrichm_a00b21_idx",
                    ),
                    models.Index(
                        fields=["item", "created_at"],
                        name="myapp_iteme_item_id_9cb165_idx",
                    ),
                ],
            },
        ),
    ]
