# Generated by Django 5.2.16 on 2026-07-27 08:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0089_item_enrichment_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ocr", "OCR Rescan - Extract from attached documents"),
                            (
                                "validation",
                                "Validation & Normalization - Correct existing data",
                            ),
                            (
                                "merchant_lookup",
                                "Merchant Lookup - Infer from similar items",
                            ),
                        ],
                        help_text="Which enrichment method this config applies to.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable scheduled enrichment for this method.",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("daily", "Every Day at 2 AM"),
                            ("weekly", "Every Monday at 2 AM"),
                            ("biweekly", "Every 2 Weeks at 2 AM"),
                            ("monthly", "First of Month at 2 AM"),
                            ("disabled", "Disabled"),
                        ],
                        default="disabled",
                        help_text="How often to run scheduled enrichment.",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.5"),
                        help_text="Minimum confidence score to apply enrichment (0-1).",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "auto_apply",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically apply changes without admin approval (if False, shows preview).",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Enrichment Configurations",
            },
        ),
        migrations.CreateModel(
            name="EnrichmentRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ocr", "OCR Rescan - Extract from attached documents"),
                            (
                                "validation",
                                "Validation & Normalization - Correct existing data",
                            ),
                            (
                                "merchant_lookup",
                                "Merchant Lookup - Infer from similar items",
                            ),
                        ],
                        help_text="Which enrichment method was run.",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval - Preview ready"),
                            ("approved", "Approved - Changes applied"),
                            ("rejected", "Rejected - Changes not applied"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="in_progress",
                        help_text="Current status of this enrichment run.",
                        max_length=50,
                    ),
                ),
                (
                    "total_items",
                    models.PositiveIntegerField(
                        default=0, help_text="Total items processed in this run."
                    ),
                ),
                (
                    "successful_items",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Items with at least one successful enrichment.",
                    ),
                ),
                (
                    "total_changes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total field changes made across all items.",
                    ),
                ),
                (
                    "average_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        help_text="Average confidence score of all changes.",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "confidence_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.5"),
                        help_text="Confidence threshold used for this run.",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Admin notes about this run (e.g., rejection reason).",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved this enrichment run.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_enrichment_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrichmentRunItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=False,
                        help_text="Whether enrichment was successful for this item.",
                    ),
                ),
                (
                    "changes_proposed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of field changes proposed for this item.",
                    ),
                ),
                (
                    "changes_applied",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of field changes actually applied."
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if enrichment failed for this item.",
                    ),
                ),
                (
                    "preview_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON preview of proposed changes before approval.",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_run_results",
                        to="myapp.item",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="myapp.enrichmentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-run__started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="enrichmentrun",
            index=models.Index(
                fields=["status", "started_at"], name="myapp_enric_status_d4943c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrichmentrun",
            index=models.Index(
                fields=["method", "started_at"], name="myapp_enric_method_b648c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrichmentrunitem",
            index=models.Index(
                fields=["run", "item"], name="myapp_enric_run_id_fe2356_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrichmentrunitem",
            unique_together={("run", "item")},
        ),
    ]
