# Generated by Django 5.2.16 on 2026-07-27 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0090_enrichmentconfig_enrichmentrun_enrichmentrunitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrichmentFieldPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ocr", "OCR Rescan - Extract from attached documents"),
                            (
                                "validation",
                                "Validation & Normalization - Correct existing data",
                            ),
                            (
                                "merchant_lookup",
                                "Merchant Lookup - Infer from similar items",
                            ),
                        ],
                        help_text="Enrichment method this preference applies to.",
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("name", "Name"),
                            ("issuer", "Issuer"),
                            ("value", "Value"),
                            ("currency", "Currency"),
                            ("expiry_date", "Expiry Date"),
                            ("description", "Description"),
                            ("notes", "Notes"),
                            ("balance_check_url", "Balance Check URL"),
                            ("type", "Type"),
                        ],
                        help_text="Field to exclude from enrichment.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_field_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "method"], name="myapp_enric_user_id_a1784d_idx"
                    )
                ],
                "unique_together": {("user", "method", "field_name")},
            },
        ),
    ]
