# Generated by Django 5.2.16 on 2026-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0091_enrichmentfieldpreference"),
    ]

    operations = [
        # Transaction indexes — covers wallet budget queries, balance calculations, analytics
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['item', 'date'], name='transaction_item_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'value'], name='transaction_date_value'),
        ),

        # Document indexes — covers item detail page queries
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['item'], name='document_item'),
        ),

        # WalletActivity indexes — covers activity feed queries
        migrations.AddIndex(
            model_name='walletactivity',
            index=models.Index(fields=['wallet', 'timestamp'], name='walletactivity_wallet_time'),
        ),

        # LoginAuditLog indexes — covers security audit queries
        migrations.AddIndex(
            model_name='loginauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='loginauditlog_user_time'),
        ),
    ]
