# Generated by Django 5.2.16 on 2026-07-27 14:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0092_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=3
                    ),
                ),
                ("inferred_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("expires_soon", "Expires within 7 days"),
                            ("expires_very_soon", "Expires today or tomorrow"),
                            ("low_balance", "Balance below £5"),
                            ("unused", "Unused for 6+ months"),
                            ("budget_overspend", "Category overspending"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "action",
                    models.CharField(help_text="Suggested action text", max_length=255),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")]
                    ),
                ),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WalletBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_limit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "alert_threshold",
                    models.IntegerField(
                        default=80, help_text="Alert when spend reaches X% of limit"
                    ),
                ),
                (
                    "current_month_spent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        # Plain RemoveIndex emits a bare DROP INDEX with no IF EXISTS guard.
        # On at least one production deploy, 0092 (which is supposed to have
        # created these five) never actually committed - so the DROP here
        # hit a missing index, and since SQLite migrations are atomic, that
        # single failure rolled back this entire migration, silently taking
        # the ItemCategory/ItemRecommendation/WalletBudget CreateModel
        # operations down with it every time this migration was retried.
        # SeparateDatabaseAndState keeps Django's migration *state* in sync
        # (so future makemigrations still sees these indexes as gone) while
        # making the actual DB operation tolerant of the index already
        # being absent, on both SQLite and Postgres.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(model_name="document", name="document_item"),
                migrations.RemoveIndex(
                    model_name="loginauditlog", name="loginauditlog_user_time"
                ),
                migrations.RemoveIndex(
                    model_name="transaction", name="transaction_item_date"
                ),
                migrations.RemoveIndex(
                    model_name="transaction", name="transaction_date_value"
                ),
                migrations.RemoveIndex(
                    model_name="walletactivity", name="walletactivity_wallet_time"
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "document_item";',
                    reverse_sql='CREATE INDEX IF NOT EXISTS "document_item" ON "myapp_document" ("item_id");',
                ),
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "loginauditlog_user_time";',
                    reverse_sql='CREATE INDEX IF NOT EXISTS "loginauditlog_user_time" ON "myapp_loginauditlog" ("user_id", "timestamp");',
                ),
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "transaction_item_date";',
                    reverse_sql='CREATE INDEX IF NOT EXISTS "transaction_item_date" ON "myapp_transaction" ("item_id", "date");',
                ),
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "transaction_date_value";',
                    reverse_sql='CREATE INDEX IF NOT EXISTS "transaction_date_value" ON "myapp_transaction" ("date", "value");',
                ),
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "walletactivity_wallet_time";',
                    reverse_sql='CREATE INDEX IF NOT EXISTS "walletactivity_wallet_time" ON "myapp_walletactivity" ("wallet_id", "timestamp");',
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemcategory",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="myapp.item",
            ),
        ),
        migrations.AddField(
            model_name="itemrecommendation",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="myapp.item",
            ),
        ),
        migrations.AddField(
            model_name="walletbudget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="walletbudget",
            name="wallet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget",
                to="myapp.wallet",
            ),
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(
                fields=["item", "category"], name="myapp_itemc_item_id_d1e8d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemrecommendation",
            index=models.Index(
                fields=["item", "dismissed_at"], name="myapp_itemr_item_id_30ab39_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="itemrecommendation",
            unique_together={("item", "reason")},
        ),
        migrations.AlterUniqueTogether(
            name="walletbudget",
            unique_together={("wallet", "user")},
        ),
    ]
