# Generated by Django 5.2.16 on 2026-07-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0093_itemcategory_itemrecommendation_walletbudget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemenrichmentlog",
            name="enrichment_type",
            field=models.CharField(
                choices=[
                    ("ocr_rescan", "OCR Rescan - Re-extracted from attached document"),
                    (
                        "merchant_lookup",
                        "Merchant Lookup - Matched against merchant database",
                    ),
                    ("validation", "Validation - Normalized/corrected field values"),
                    (
                        "auto_enrich",
                        "Auto Enrichment - Populated from enrichment pipeline",
                    ),
                    (
                        "flagged",
                        "Flagged for Review - Suspicious value noted, not auto-changed",
                    ),
                ],
                help_text="What type of enrichment produced this change.",
                max_length=50,
            ),
        ),
    ]
