# Generated by Django 5.2.16 on 2026-07-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0094_alter_itemenrichmentlog_enrichment_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WalletBudget",
        ),
    ]
