# Generated by Django 5.2.16 on 2026-07-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0095_delete_walletbudget"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanfieldcorrection",
            name="enrichment_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which enrichment method (ocr_rescan/validation/merchant_lookup/auto_enrich) produced the corrected-away value, if source='enrichment'.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="scanfieldcorrection",
            name="source",
            field=models.CharField(
                choices=[
                    ("scan", "AI Photo Scan"),
                    ("suggestion", "Accepted Field Suggestion"),
                    ("enrichment", "Enrichment Pipeline"),
                ],
                default="scan",
                max_length=20,
            ),
        ),
    ]
