# Generated by Django 5.2.16 on 2026-07-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0096_scanfieldcorrection_enrichment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrichmentfieldpreference",
            name="reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Set automatically when the enrichment circuit breaker auto-disables a field after repeated corrections; blank when a user chose this manually.",
                max_length=255,
            ),
        ),
    ]
