# Generated by Django 5.2.16 on 2026-07-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0097_enrichmentfieldpreference_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrecommendation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("expires_soon", "Expires within 7 days"),
                    ("expires_very_soon", "Expires today or tomorrow"),
                    ("low_balance", "Balance below £5"),
                    ("unused", "Unused for 6+ months"),
                    ("budget_overspend", "Category overspending"),
                    ("needs_review", "Enrichment flagged a field for review"),
                ],
                max_length=30,
            ),
        ),
    ]
