# Generated by Django 5.2.16 on 2026-08-01 15:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0098_alter_itemrecommendation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="custom_recommendation_thresholds_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Override the default Smart Suggestions thresholds below. When off, the site-wide defaults are used (expiring within 7 days, expiring within 1 day as urgent, balance under £5, unused for 6 months).",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="recommendation_expiry_soon_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Suggest using an item when it expires within this many days.",
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="recommendation_expiry_urgent_days",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Flag an item as urgent (expires very soon) within this many days.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="recommendation_low_balance_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Suggest using a gift card/voucher when its balance drops below this amount.",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("1000.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="recommendation_unused_months",
            field=models.PositiveSmallIntegerField(
                default=6,
                help_text="Suggest archiving an item once it hasn't been used for this many months.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(36),
                ],
            ),
        ),
    ]
