# Generated by Django 5.2.16 on 2026-08-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0099_userpreference_custom_recommendation_thresholds_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="itemshare",
            name="role",
            field=models.CharField(
                choices=[("viewer", "Viewer"), ("editor", "Editor")],
                default="editor",
                max_length=10,
            ),
        ),
    ]
