# Generated by Django 5.2.16 on 2026-08-05 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0101_itemcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scanfieldcorrection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="scanfieldcorrection",
            name="issuer",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="scanfieldcorrection",
            unique_together={("user", "item_type", "issuer", "field", "ai_value")},
        ),
    ]
