# Generated by Django 5.2.16 on 2026-08-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0102_alter_scanfieldcorrection_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalScanCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(max_length=100)),
                ("issuer", models.CharField(max_length=255)),
                ("field", models.CharField(max_length=50)),
                ("ai_value", models.CharField(max_length=255)),
                ("corrected_value", models.CharField(max_length=255)),
                (
                    "confirmed_by_users",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many distinct users' own corrections agreed on this mapping the last time detect_systemic_misreads() ran.",
                    ),
                ),
                ("promoted_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-confirmed_by_users", "-promoted_at"],
                "unique_together": {("item_type", "issuer", "field", "ai_value")},
            },
        ),
    ]
