# Generated by Django 5.2.16 on 2026-08-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0103_globalscancorrection"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="budget_alert_sent_for_month",
            field=models.DateField(
                blank=True,
                help_text="First-of-month date the budget_overspend alert was last sent for - prevents re-firing on every periodic check while still over budget, and naturally resets once a new calendar month starts.",
                null=True,
            ),
        ),
    ]
