# Generated by Django 5.2.16 on 2026-08-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0104_wallet_budget_alert_sent_for_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalscancorrection",
            name="last_applied_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this pattern last healed a live scan. Never set means it's been promoted but never actually fired yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalscancorrection",
            name="times_applied",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many times this cross-user pattern has actually healed a live scan for someone who'd never taught it personally (see apply_learned_corrections).",
            ),
        ),
        migrations.AddField(
            model_name="scanfieldcorrection",
            name="last_applied_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this correction last healed a live scan. Never set means it's been taught but never actually fired yet.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scanfieldcorrection",
            name="times_applied",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many times this correction has actually healed a live scan (see apply_learned_corrections) - distinct from times_seen, which counts how often the user re-taught it at save time, not how often it's fired at scan time.",
            ),
        ),
    ]
