# Generated by Django 5.2.16 on 2026-08-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0105_globalscancorrection_last_applied_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichmentconfig",
            name="method",
            field=models.CharField(
                choices=[
                    ("ocr", "OCR Rescan - Extract from attached documents"),
                    (
                        "validation",
                        "Validation & Normalization - Correct existing data",
                    ),
                    ("merchant_lookup", "Merchant Lookup - Infer from similar items"),
                    (
                        "learned_correction",
                        "Retroactive Correction Sweep - Apply already-known corrections to existing items",
                    ),
                ],
                help_text="Which enrichment method this config applies to.",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="enrichmentfieldpreference",
            name="method",
            field=models.CharField(
                choices=[
                    ("ocr", "OCR Rescan - Extract from attached documents"),
                    (
                        "validation",
                        "Validation & Normalization - Correct existing data",
                    ),
                    ("merchant_lookup", "Merchant Lookup - Infer from similar items"),
                    (
                        "learned_correction",
                        "Retroactive Correction Sweep - Apply already-known corrections to existing items",
                    ),
                ],
                help_text="Enrichment method this preference applies to.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="enrichmentrun",
            name="method",
            field=models.CharField(
                choices=[
                    ("ocr", "OCR Rescan - Extract from attached documents"),
                    (
                        "validation",
                        "Validation & Normalization - Correct existing data",
                    ),
                    ("merchant_lookup", "Merchant Lookup - Infer from similar items"),
                    (
                        "learned_correction",
                        "Retroactive Correction Sweep - Apply already-known corrections to existing items",
                    ),
                ],
                help_text="Which enrichment method was run.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="itemenrichmentlog",
            name="enrichment_type",
            field=models.CharField(
                choices=[
                    ("ocr_rescan", "OCR Rescan - Re-extracted from attached document"),
                    (
                        "merchant_lookup",
                        "Merchant Lookup - Matched against merchant database",
                    ),
                    ("validation", "Validation - Normalized/corrected field values"),
                    (
                        "auto_enrich",
                        "Auto Enrichment - Populated from enrichment pipeline",
                    ),
                    (
                        "learned_correction",
                        "Retroactive Correction - Healed using an already-known correction",
                    ),
                    (
                        "flagged",
                        "Flagged for Review - Suspicious value noted, not auto-changed",
                    ),
                ],
                help_text="What type of enrichment produced this change.",
                max_length=50,
            ),
        ),
    ]
