# Generated by Django 5.2.16 on 2026-08-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0106_alter_enrichmentconfig_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanfieldcorrection",
            name="enrichment_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which enrichment method (ocr_rescan/validation/merchant_lookup/auto_enrich/learned_correction) produced the corrected-away value, if source='enrichment'.",
                max_length=50,
            ),
        ),
    ]
