# Generated by Django 5.2.16 on 2026-08-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0107_alter_scanfieldcorrection_enrichment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalscancorrection",
            name="stale_alerted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When an admin was last alerted that this pattern had gone stale (see flag_stale_corrections_task). Cleared automatically the next time this pattern actually fires, so it can be reported again if it goes stale a second time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scanfieldcorrection",
            name="stale_alerted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When an admin was last alerted that this correction had gone stale (see flag_stale_corrections_task). Cleared automatically the next time this correction actually fires, so a correction that goes stale again later is reported as a genuinely new episode rather than staying silently suppressed.",
                null=True,
            ),
        ),
    ]
