# Generated by Django 5.2.16 on 2026-08-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0108_globalscancorrection_stale_alerted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="company_status",
            field=models.CharField(
                blank=True,
                help_text="Last known Companies House company status for this issuer (see notify.tasks.check_merchant_health), e.g. 'active' or 'administration'.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="health_checked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When company_status/is_unhealthy were last refreshed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="is_unhealthy",
            field=models.BooleanField(
                default=False,
                help_text="True if company_status was a bad status (dissolved/liquidation/administration/etc.) at high confidence as of the last health check. Cleared automatically if the company's status later recovers.",
            ),
        ),
    ]
