import uuid
from django.urls import path, include
from . import views
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = (
    path("dashboard", views.dashboard, name="dashboard"),
    path('', views.show_items, name='show_items'),
    path('offline/', views.offline, name='offline'),
    path('ping/', views.ping, name='ping'),
    path('items/create/', views.create_item, name='create_item'),
    path('items/lookup-merchant-balance-url/', views.lookup_merchant_balance_url, name='lookup_merchant_balance_url'),
    path('items/suggest-field-options/', views.suggest_field_options, name='suggest_field_options'),
    path('items/check-duplicate/', views.check_duplicate_code, name='check_duplicate_code'),
    path('items/check-duplicate-image/', views.check_duplicate_image, name='check_duplicate_image'),
    path('items/view/<uuid:item_uuid>', views.view_item, name='view_item'),
    path('items/edit/<uuid:item_uuid>', views.edit_item, name='edit_item'),
    path('items/duplicate/<uuid:item_uuid>', views.duplicate_item, name='duplicate_item'),
    path('items/delete/<uuid:item_uuid>', views.delete_item, name='delete_item'),
    path('items/toggle_status/<uuid:item_id>', views.toggle_item_status, name='toggle_item_status'),
    path('items/toggle_pin/<uuid:item_uuid>', views.toggle_pin_item, name='toggle_pin_item'),
    path('items/toggle_archive/<uuid:item_uuid>', views.toggle_archive_item, name='toggle_archive_item'),
    path('items/toggle_mute/<uuid:item_uuid>', views.toggle_mute_notifications, name='toggle_mute_notifications'),
    path('nearby-items/', views.nearby_items, name='nearby_items'),
    path('items/bulk-archive/', views.bulk_archive_items, name='bulk_archive_items'),
    path('items/bulk-unarchive/', views.bulk_unarchive_items, name='bulk_unarchive_items'),
    path('items/bulk-delete/', views.bulk_delete_items, name='bulk_delete_items'),
    path('items/bulk-tag/', views.bulk_tag_items, name='bulk_tag_items'),
    path('items/bulk-move/', views.bulk_move_items, name='bulk_move_items'),
    path('items/bulk-currency/', views.bulk_currency_items, name='bulk_currency_items'),
    path('items/share/<uuid:item_id>', views.share_item_view, name='share_item'),
    path('items/unshare/<uuid:item_id>/<int:user_id>', views.unshare_item, name='unshare_item'),
    path('items/<uuid:item_id>/public-share/', views.get_public_share_link, name='get_public_share_link'),
    path('items/<uuid:item_id>/public-share/regenerate/', views.regenerate_public_share_link, name='regenerate_public_share_link'),
    path('items/<uuid:item_id>/public-share/revoke/', views.revoke_public_share_link, name='revoke_public_share_link'),
    path('items/<uuid:item_id>/share-logo/', views.item_share_logo, name='item_share_logo'),
    path('s/<uuid:share_id>/', views.public_item_share, name='public_item_share'),
    path('s/<uuid:share_id>/logo/', views.public_item_share_logo, name='public_item_share_logo'),
    path('s/<uuid:share_id>/pkpass/', views.public_item_pkpass, name='public_item_pkpass'),
    path('items/view-image/<uuid:item_id>/', views.serve_image_file, name='serve_image_file'),
    path('items/barcode-push/<uuid:item_id>/', views.barcode_push_image, name='barcode_push_image'),
    path('items/view-file/<uuid:item_id>/', views.view_original_file, name='view_original_file'),
    path('items/<uuid:item_uuid>/documents/upload', views.upload_document, name='upload_document'),
    path('documents/<int:document_id>/download', views.download_document, name='download_document'),
    path('documents/<int:document_id>/view', views.view_document_file, name='view_document_file'),
    path('documents/<int:document_id>/delete', views.delete_document, name='delete_document'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('post-logout/', views.post_logout, name='post_logout'),
    path('user/edit/notifications', views.update_apprise_urls, name='update_apprise_urls'),
    path('user/toggle_view_mode', views.toggle_view_mode, name='toggle_view_mode'),
    path('transactions/delete/<uuid:transaction_id>', views.delete_transaction, name='delete_transaction'),
    path('transactions/update-date/<uuid:transaction_id>', views.update_transaction_date, name='update_transaction_date'),
    path('verify-apprise-urls/', views.verify_apprise_urls, name='verify_apprise_urls'),
    path('download/<uuid:item_id>/', views.download_file, name='download_file'),
    path('shared-items/', views.sharing_center, name='sharing_center'),
    path('api/get/stats', views.get_stats, name='get_stats'),
    path('user/edit/preferences', views.update_user_preferences, name='update_user_preferences'),
    path('user/api-access/', views.api_access, name='api_access'),
    path('developer/', views.developer_hub, name='developer_hub'),
    path('developer/webhook/create/', views.developer_hub_webhook_create, name='developer_hub_webhook_create'),
    path('developer/webhook/<int:webhook_id>/edit/', views.developer_hub_webhook_edit, name='developer_hub_webhook_edit'),
    path('developer/webhook/<int:webhook_id>/delete/', views.developer_hub_webhook_delete, name='developer_hub_webhook_delete'),
    path('developer/webhook/<int:webhook_id>/test/', views.developer_hub_webhook_test, name='developer_hub_webhook_test'),
    path('developer/test-companies-house/', views.test_companies_house_key, name='test_companies_house_key'),
    path('developer/test-logo-dev/', views.test_logo_dev_key, name='test_logo_dev_key'),
    path('developer/merchant-health/', views.check_merchant_health_status, name='check_merchant_health_status'),
    path('wallets/', views.manage_wallets, name='manage_wallets'),
    path('wallets/reorder/', views.wallet_reorder, name='wallet_reorder'),
    path('wallets/<int:wallet_id>/edit', views.edit_wallet, name='edit_wallet'),
    path('wallets/<int:wallet_id>/delete', views.delete_wallet, name='delete_wallet'),
    path('wallets/<int:wallet_id>/share', views.share_wallet, name='share_wallet'),
    path('wallets/<int:wallet_id>/unshare/<int:user_id>', views.unshare_wallet, name='unshare_wallet'),
    path('wallets/<int:wallet_id>/leave', views.leave_shared_wallet, name='leave_shared_wallet'),
    path('tags/', views.manage_tags, name='manage_tags'),
    path('tags/<int:tag_id>/edit', views.edit_tag, name='edit_tag'),
    path('tags/<int:tag_id>/delete', views.delete_tag, name='delete_tag'),
    path('analytics/', views.analytics, name='analytics'),
    path('webhooks/', views.manage_webhooks, name='manage_webhooks'),
    path('webhooks/create/', views.create_webhook, name='create_webhook'),
    path('webhooks/<int:webhook_id>/edit/', views.edit_webhook, name='edit_webhook'),
    path('webhooks/<int:webhook_id>/delete/', views.delete_webhook, name='delete_webhook'),
    path('webhooks/<int:webhook_id>/test/', views.test_webhook, name='test_webhook'),
    path('wallets/<int:wallet_id>/activity/', views.wallet_activity_feed, name='wallet_activity_feed'),
    path('user/security/', views.session_management, name='session_management'),
    path('user/security/revoke-session/', views.revoke_session, name='revoke_session'),
    path('user/security/download-my-data/', views.gdpr_data_export, name='gdpr_data_export'),
    path('user/security/totp/setup/', views.totp_setup, name='totp_setup'),
    path('user/security/totp/verify/', views.totp_verify, name='totp_verify'),
    path('user/security/totp/disable/', views.totp_disable, name='totp_disable'),
    path('expiry-timeline/', views.expiry_timeline, name='expiry_timeline'),
    path('calendar/download/', views.download_ics, name='download_ics'),
    path('calendar/regenerate-token/', views.regenerate_ics_token, name='regenerate_ics_token'),
    path('calendar/<uuid:token>.ics', views.ics_feed, name='ics_feed'),
    path('admin-tools/redeploy/', views.trigger_portainer_redeploy, name='trigger_portainer_redeploy'),
    path('admin-tools/check-for-updates/', views.trigger_update_check, name='trigger_update_check'),
    path('admin-tools/check-upstream/', views.trigger_upstream_check, name='trigger_upstream_check'),
    path('admin-tools/site-settings/', views.site_settings, name='site_settings'),
    path('admin-tools/help/<str:doc_slug>/', views.view_doc, name='view_doc'),
    path('help/', views.help_center, name='help_center'),
    path('help/field-map/', views.field_map, name='field_map'),
    path('barcode/decode/', views.barcode_decode, name='barcode_decode'),
    # #5: Bulk export
    path('items/export/csv/', views.export_selected_csv, name='export_selected_csv'),
    path('items/export/json/', views.export_selected_json, name='export_selected_json'),
    # #11: Inline balance editing
    path('items/<uuid:item_uuid>/update-balance/', views.update_item_balance, name='update_item_balance'),
    # #16: Regenerate TOTP backup codes
    path('user/security/totp/regenerate-backup-codes/', views.regenerate_totp_backup_codes, name='regenerate_totp_backup_codes'),
    # Invite links
    path('admin-tools/invites/', views.manage_invites, name='manage_invites'),
    path('invite/<uuid:token>/', views.accept_invite, name='accept_invite'),
    # Users panel (superuser)
    path('admin-tools/users/', views.manage_users, name='manage_users'),
    path('admin-tools/users/toggle-superuser/', views.toggle_user_superuser, name='toggle_user_superuser'),
    # OIDC identity management
    path('user/security/unlink-oidc/', views.unlink_oidc, name='unlink_oidc'),
)

admin.site.site_header = "VoucherVault Plus+"
admin.site.site_title = "VoucherVault Plus+"
admin.site.index_title = "Welcome to VoucherVault Plus+"
