# Generated by Django 5.2.15 on 2026-07-16 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0056_siteconfiguration_calendar_months_ahead_and_more"),
        ("notify", "0002_alter_notificationrule_backend_webpushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrule",
            name="digest_frequency",
            field=models.CharField(
                choices=[("immediate", "Immediate"), ("daily", "Daily Digest")],
                default="immediate",
                help_text='"Daily Digest" batches matching events into one combined message sent once a day instead of pinging for each one separately.',
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DigestEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.item",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digest_entries",
                        to="notify.notificationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
