# Generated by Django 5.2.16 on 2026-07-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0003_notificationrule_digest_frequency_digestentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="backend",
            field=models.CharField(
                choices=[
                    ("apprise", "Apprise URL"),
                    ("firefly", "Firefly III"),
                    ("ntfy", "ntfy"),
                    ("webhook", "Webhook (n8n etc.)"),
                    ("webpush", "Web Push"),
                ],
                max_length=20,
            ),
        ),
    ]
