# Generated by Django 5.2.16 on 2026-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0004_firefly_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationrule",
            name="apply_to_all",
            field=models.BooleanField(
                default=False,
                help_text="Apply this rule to every item owned by the user — no per-item rule needed. When off, the rule only fires for items explicitly wired to a notification rule.",
            ),
        ),
    ]
