# Generated by Django 5.2.16 on 2026-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0005_notificationrule_apply_to_all"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrule",
            name="backend",
            field=models.CharField(
                choices=[
                    ("apprise", "Apprise URL"),
                    ("discord", "Discord"),
                    ("email", "Email (SMTP)"),
                    ("firefly", "Firefly III"),
                    ("ntfy", "ntfy"),
                    ("telegram", "Telegram"),
                    ("webhook", "Webhook (n8n etc.)"),
                    ("webpush", "Web Push"),
                ],
                max_length=20,
            ),
        ),
    ]
