# Generated by Django 5.2.16 on 2026-07-27 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0093_itemcategory_itemrecommendation_walletbudget_and_more"),
        ("notify", "0006_alter_notificationrule_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="FireflyTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firefly_transaction_id", models.IntegerField(unique=True)),
                ("firefly_account_id", models.IntegerField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firefly_transaction",
                        to="myapp.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebhookRetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("attempt", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.item",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_retries",
                        to="notify.notificationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["next_retry_at"],
                "indexes": [
                    models.Index(
                        fields=["rule", "next_retry_at"],
                        name="notify_webh_rule_id_454bf7_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notify_webh_created_e60f63_idx"
                    ),
                ],
            },
        ),
    ]
